### ISSUE TITLE
Credentials exposed

### ISSUE THREAD

**Issue by mondaysunrise** [JakubMatejka/kac-test#1]
https://github.com/JakubMatejka/kac-test/blob/739bb75fd9f4dae7b5b323bea8bd1f1a66289111/template2/main/extractor/keboola.ex-aws-s3/7241111-my-aws-s-3-data-source/config.json#L5

Hi there,

please remove your exposed credentials from your Git repository commit history, change them and externalize.

https://aws.amazon.com/blogs/security/what-to-do-if-you-inadvertently-expose-an-aws-access-key/

Cheers,

**Comment by JakubMatejka** [comment]
Hi, this is not an exposed credentials. This repository is a sample configuration for demo purposes. The linked string is a cyphered sample value (probably just a word 'token' 🙂) so no need to take any action. Thanks.
